import { Researcher } from "./researchers-data"

export const researchers: Researcher[] = [
  {
    id: 13,
    slug: "jacob-green",
    name: "Dr. Jacob Green",
    avatar: "/portraits/imgs14.jpg",
    affiliation: "EleutherAI",
    communities: ["ea", "academic", "lesswrong"],
    topics: ["Game Theory", "Natural Language Processing"],
    papers: 36,
    posts: 32,
    hIndex: 59,
    bio: "Researcher at Oxford FHI focusing on game theory and natural language processing.",
    fullBio: "Dr. Jacob Green is a researcher specializing in game theory, natural language processing. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://jacob-green.com",
    twitter: "jacobgreen",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 14,
    slug: "diana-garcia",
    name: "Dr. Diana Garcia",
    avatar: "/portraits/imgs1.jpg",
    affiliation: "EleutherAI",
    communities: ["lesswrong", "academic", "ea"],
    topics: ["Large Language Models", "Game Theory", "Interpretability", "Robotics"],
    papers: 106,
    posts: 3,
    hIndex: 43,
    bio: "Researcher at Stanford HAI focusing on large language models and game theory.",
    fullBio: "Dr. Diana Garcia is a researcher specializing in large language models, game theory, interpretability, robotics. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://diana-garcia.com",
    twitter: "dianagarcia",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 15,
    slug: "jerry-hernandez",
    name: "Dr. Jerry Hernandez",
    avatar: "/portraits/imgs2.jpg",
    affiliation: "Google DeepMind",
    communities: ["lesswrong", "academic"],
    topics: ["Reinforcement Learning", "Decision Theory"],
    papers: 117,
    posts: 13,
    hIndex: 49,
    bio: "Researcher at Allen Institute for AI focusing on reinforcement learning and decision theory.",
    fullBio: "Dr. Jerry Hernandez is a researcher specializing in reinforcement learning, decision theory. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://jerry-hernandez.com",
    twitter: "jerryhernandez",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 16,
    slug: "isabella-alexander",
    name: "Dr. Isabella Alexander",
    avatar: "/portraits/imgs3.jpg",
    affiliation: "UC Berkeley",
    communities: ["academic"],
    topics: ["Ethics", "Large Language Models", "Interpretability"],
    papers: 8,
    posts: 23,
    hIndex: 55,
    bio: "Researcher at Stanford HAI focusing on ethics and large language models.",
    fullBio: "Dr. Isabella Alexander is a researcher specializing in ethics, large language models, interpretability. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://isabella-alexander.com",
    twitter: "isabellaalexander",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 17,
    slug: "sean-martinez",
    name: "Dr. Sean Martinez",
    avatar: "/portraits/imgs4.jpg",
    affiliation: "OpenAI",
    communities: ["ea", "academic"],
    topics: ["Decision Theory", "Natural Language Processing", "Robotics", "Computer Vision"],
    papers: 55,
    posts: 34,
    hIndex: 45,
    bio: "Researcher at Carnegie Mellon University focusing on decision theory and natural language processing.",
    fullBio: "Dr. Sean Martinez is a researcher specializing in decision theory, natural language processing, robotics, computer vision. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://sean-martinez.com",
    twitter: "seanmartinez",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 18,
    slug: "madison-mitchell",
    name: "Dr. Madison Mitchell",
    avatar: "/portraits/imgs5.jpg",
    affiliation: "Stanford HAI",
    communities: ["lesswrong"],
    topics: ["Interpretability", "Computer Vision"],
    papers: 12,
    posts: 5,
    hIndex: 56,
    bio: "Researcher at Google DeepMind focusing on interpretability and computer vision.",
    fullBio: "Dr. Madison Mitchell is a researcher specializing in interpretability, computer vision. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://madison-mitchell.com",
    twitter: "madisonmitchell",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 19,
    slug: "maria-rogers",
    name: "Dr. Maria Rogers",
    avatar: "/portraits/imgs6.jpg",
    affiliation: "MIT CSAIL",
    communities: ["ea"],
    topics: ["Neural Networks", "Game Theory", "Natural Language Processing", "Reinforcement Learning"],
    papers: 9,
    posts: 29,
    hIndex: 41,
    bio: "Researcher at OpenAI focusing on neural networks and game theory.",
    fullBio: "Dr. Maria Rogers is a researcher specializing in neural networks, game theory, natural language processing, reinforcement learning. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://maria-rogers.com",
    twitter: "mariarogers",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 20,
    slug: "amy-cox",
    name: "Dr. Amy Cox",
    avatar: "/portraits/imgs7.jpg",
    affiliation: "MIRI",
    communities: ["lesswrong"],
    topics: ["Natural Language Processing", "Neural Networks"],
    papers: 94,
    posts: 3,
    hIndex: 51,
    bio: "Researcher at Google DeepMind focusing on natural language processing and neural networks.",
    fullBio: "Dr. Amy Cox is a researcher specializing in natural language processing, neural networks. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://amy-cox.com",
    twitter: "amycox",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 21,
    slug: "charles-wright",
    name: "Dr. Charles Wright",
    avatar: "/portraits/imgs8.jpg",
    affiliation: "OpenAI",
    communities: ["academic", "ea", "lesswrong"],
    topics: ["Ethics", "Natural Language Processing", "Decision Theory", "AI Governance"],
    papers: 61,
    posts: 17,
    hIndex: 52,
    bio: "Researcher at Oxford FHI focusing on ethics and natural language processing.",
    fullBio: "Dr. Charles Wright is a researcher specializing in ethics, natural language processing, decision theory, ai governance. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://charles-wright.com",
    twitter: "charleswright",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 22,
    slug: "samuel-james",
    name: "Dr. Samuel James",
    avatar: "/portraits/imgs9.jpg",
    affiliation: "Carnegie Mellon University",
    communities: ["academic", "lesswrong", "ea"],
    topics: ["Neural Networks", "Game Theory"],
    papers: 74,
    posts: 24,
    hIndex: 11,
    bio: "Researcher at Carnegie Mellon University focusing on neural networks and game theory.",
    fullBio: "Dr. Samuel James is a researcher specializing in neural networks, game theory. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://samuel-james.com",
    twitter: "samueljames",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 23,
    slug: "roy-anderson",
    name: "Dr. Roy Anderson",
    avatar: "/portraits/imgs10.jpg",
    affiliation: "MIRI",
    communities: ["ea", "lesswrong", "academic"],
    topics: ["Computer Vision", "Robotics"],
    papers: 109,
    posts: 15,
    hIndex: 34,
    bio: "Researcher at Oxford FHI focusing on computer vision and robotics.",
    fullBio: "Dr. Roy Anderson is a researcher specializing in computer vision, robotics. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://roy-anderson.com",
    twitter: "royanderson",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 24,
    slug: "emily-cooper",
    name: "Dr. Emily Cooper",
    avatar: "/portraits/imgs11.jpg",
    affiliation: "OpenAI",
    communities: ["lesswrong", "ea", "academic"],
    topics: ["Interpretability", "Reinforcement Learning", "Neural Networks", "Robotics"],
    papers: 98,
    posts: 49,
    hIndex: 53,
    bio: "Researcher at University of Toronto focusing on interpretability and reinforcement learning.",
    fullBio: "Dr. Emily Cooper is a researcher specializing in interpretability, reinforcement learning, neural networks, robotics. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://emily-cooper.com",
    twitter: "emilycooper",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 25,
    slug: "sophia-harris",
    name: "Dr. Sophia Harris",
    avatar: "/portraits/imgs12.jpg",
    affiliation: "Anthropic",
    communities: ["ea"],
    topics: ["AI Safety", "Large Language Models"],
    papers: 113,
    posts: 7,
    hIndex: 53,
    bio: "Researcher at University of Toronto focusing on ai safety and large language models.",
    fullBio: "Dr. Sophia Harris is a researcher specializing in ai safety, large language models. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://sophia-harris.com",
    twitter: "sophiaharris",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 26,
    slug: "terry-martin",
    name: "Dr. Terry Martin",
    avatar: "/portraits/imgs13.jpg",
    affiliation: "University of Toronto",
    communities: ["academic", "lesswrong", "ea"],
    topics: ["Ethics", "AI Governance"],
    papers: 87,
    posts: 43,
    hIndex: 13,
    bio: "Researcher at EleutherAI focusing on ethics and ai governance.",
    fullBio: "Dr. Terry Martin is a researcher specializing in ethics, ai governance. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://terry-martin.com",
    twitter: "terrymartin",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 27,
    slug: "christopher-cooper",
    name: "Dr. Christopher Cooper",
    avatar: "/portraits/imgs15.jpg",
    affiliation: "Anthropic",
    communities: ["lesswrong", "ea"],
    topics: ["Computer Vision", "Large Language Models"],
    papers: 46,
    posts: 0,
    hIndex: 59,
    bio: "Researcher at EleutherAI focusing on computer vision and large language models.",
    fullBio: "Dr. Christopher Cooper is a researcher specializing in computer vision, large language models. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://christopher-cooper.com",
    twitter: "christophercooper",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 28,
    slug: "diane-bryant",
    name: "Dr. Diane Bryant",
    avatar: "/portraits/imgs16.jpg",
    affiliation: "MIRI",
    communities: ["ea"],
    topics: ["Ethics", "Neural Networks", "Computer Vision"],
    papers: 40,
    posts: 47,
    hIndex: 41,
    bio: "Researcher at Google DeepMind focusing on ethics and neural networks.",
    fullBio: "Dr. Diane Bryant is a researcher specializing in ethics, neural networks, computer vision. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://diane-bryant.com",
    twitter: "dianebryant",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 29,
    slug: "virginia-anderson",
    name: "Dr. Virginia Anderson",
    avatar: "/portraits/imgs17.jpg",
    affiliation: "Google DeepMind",
    communities: ["academic", "ea", "lesswrong"],
    topics: ["Game Theory", "Ethics", "AI Governance"],
    papers: 134,
    posts: 10,
    hIndex: 33,
    bio: "Researcher at OpenAI focusing on game theory and ethics.",
    fullBio: "Dr. Virginia Anderson is a researcher specializing in game theory, ethics, ai governance. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://virginia-anderson.com",
    twitter: "virginiaanderson",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 30,
    slug: "nathan-rivera",
    name: "Dr. Nathan Rivera",
    avatar: "/portraits/imgs18.jpg",
    affiliation: "Anthropic",
    communities: ["ea", "lesswrong", "academic"],
    topics: ["Large Language Models", "Decision Theory", "Game Theory"],
    papers: 140,
    posts: 4,
    hIndex: 37,
    bio: "Researcher at OpenAI focusing on large language models and decision theory.",
    fullBio: "Dr. Nathan Rivera is a researcher specializing in large language models, decision theory, game theory. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://nathan-rivera.com",
    twitter: "nathanrivera",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 31,
    slug: "maria-washington",
    name: "Dr. Maria Washington",
    avatar: "/portraits/imgs19.jpg",
    affiliation: "Anthropic",
    communities: ["academic", "ea"],
    topics: ["Natural Language Processing", "Game Theory"],
    papers: 94,
    posts: 1,
    hIndex: 27,
    bio: "Researcher at UC Berkeley focusing on natural language processing and game theory.",
    fullBio: "Dr. Maria Washington is a researcher specializing in natural language processing, game theory. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://maria-washington.com",
    twitter: "mariawashington",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 32,
    slug: "patricia-ward",
    name: "Dr. Patricia Ward",
    avatar: "/portraits/imgs20.jpg",
    affiliation: "Oxford FHI",
    communities: ["lesswrong", "ea", "academic"],
    topics: ["Neural Networks", "Natural Language Processing", "AI Governance"],
    papers: 54,
    posts: 29,
    hIndex: 36,
    bio: "Researcher at MIT CSAIL focusing on neural networks and natural language processing.",
    fullBio: "Dr. Patricia Ward is a researcher specializing in neural networks, natural language processing, ai governance. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://patricia-ward.com",
    twitter: "patriciaward",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 33,
    slug: "susan-white",
    name: "Dr. Susan White",
    avatar: "/portraits/imgs21.jpg",
    affiliation: "Allen Institute for AI",
    communities: ["academic", "ea"],
    topics: ["AI Governance", "AI Safety"],
    papers: 10,
    posts: 38,
    hIndex: 40,
    bio: "Researcher at Oxford FHI focusing on ai governance and ai safety.",
    fullBio: "Dr. Susan White is a researcher specializing in ai governance, ai safety. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://susan-white.com",
    twitter: "susanwhite",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 34,
    slug: "tyler-clark",
    name: "Dr. Tyler Clark",
    avatar: "/portraits/imgs22.jpg",
    affiliation: "EleutherAI",
    communities: ["lesswrong"],
    topics: ["Ethics", "Game Theory", "AI Governance"],
    papers: 112,
    posts: 45,
    hIndex: 52,
    bio: "Researcher at MIRI focusing on ethics and game theory.",
    fullBio: "Dr. Tyler Clark is a researcher specializing in ethics, game theory, ai governance. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://tyler-clark.com",
    twitter: "tylerclark",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 35,
    slug: "sean-wilson",
    name: "Dr. Sean Wilson",
    avatar: "/portraits/imgs23.jpg",
    affiliation: "Carnegie Mellon University",
    communities: ["lesswrong"],
    topics: ["AI Safety", "Robotics"],
    papers: 45,
    posts: 35,
    hIndex: 50,
    bio: "Researcher at Anthropic focusing on ai safety and robotics.",
    fullBio: "Dr. Sean Wilson is a researcher specializing in ai safety, robotics. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://sean-wilson.com",
    twitter: "seanwilson",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 36,
    slug: "carolyn-bryant",
    name: "Dr. Carolyn Bryant",
    avatar: "/portraits/imgs24.jpg",
    affiliation: "MIRI",
    communities: ["lesswrong", "academic", "ea"],
    topics: ["AI Safety", "Computer Vision"],
    papers: 26,
    posts: 33,
    hIndex: 46,
    bio: "Researcher at MIRI focusing on ai safety and computer vision.",
    fullBio: "Dr. Carolyn Bryant is a researcher specializing in ai safety, computer vision. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://carolyn-bryant.com",
    twitter: "carolynbryant",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 37,
    slug: "jacqueline-washington",
    name: "Dr. Jacqueline Washington",
    avatar: "/portraits/imgs25.jpg",
    affiliation: "Oxford FHI",
    communities: ["academic", "ea"],
    topics: ["Neural Networks", "Game Theory", "Reinforcement Learning", "Ethics"],
    papers: 7,
    posts: 27,
    hIndex: 7,
    bio: "Researcher at Stanford HAI focusing on neural networks and game theory.",
    fullBio: "Dr. Jacqueline Washington is a researcher specializing in neural networks, game theory, reinforcement learning, ethics. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://jacqueline-washington.com",
    twitter: "jacquelinewashington",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 38,
    slug: "kelly-king",
    name: "Dr. Kelly King",
    avatar: "/portraits/imgs26.jpg",
    affiliation: "Google DeepMind",
    communities: ["lesswrong", "ea"],
    topics: ["AI Safety", "Computer Vision", "Game Theory"],
    papers: 35,
    posts: 9,
    hIndex: 22,
    bio: "Researcher at Allen Institute for AI focusing on ai safety and computer vision.",
    fullBio: "Dr. Kelly King is a researcher specializing in ai safety, computer vision, game theory. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://kelly-king.com",
    twitter: "kellyking",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 39,
    slug: "catherine-ward",
    name: "Dr. Catherine Ward",
    avatar: "/portraits/imgs27.jpg",
    affiliation: "Oxford FHI",
    communities: ["ea"],
    topics: ["Interpretability", "Game Theory"],
    papers: 140,
    posts: 5,
    hIndex: 38,
    bio: "Researcher at Anthropic focusing on interpretability and game theory.",
    fullBio: "Dr. Catherine Ward is a researcher specializing in interpretability, game theory. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://catherine-ward.com",
    twitter: "catherineward",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 40,
    slug: "michelle-jackson",
    name: "Dr. Michelle Jackson",
    avatar: "/portraits/imgs28.jpg",
    affiliation: "UC Berkeley",
    communities: ["ea", "lesswrong"],
    topics: ["Large Language Models", "AI Governance", "Game Theory", "Ethics"],
    papers: 112,
    posts: 50,
    hIndex: 38,
    bio: "Researcher at UC Berkeley focusing on large language models and ai governance.",
    fullBio: "Dr. Michelle Jackson is a researcher specializing in large language models, ai governance, game theory, ethics. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://michelle-jackson.com",
    twitter: "michellejackson",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 41,
    slug: "judith-adams",
    name: "Dr. Judith Adams",
    avatar: "/portraits/imgs29.jpg",
    affiliation: "UC Berkeley",
    communities: ["academic", "lesswrong", "ea"],
    topics: ["Natural Language Processing", "AI Safety"],
    papers: 69,
    posts: 50,
    hIndex: 58,
    bio: "Researcher at OpenAI focusing on natural language processing and ai safety.",
    fullBio: "Dr. Judith Adams is a researcher specializing in natural language processing, ai safety. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://judith-adams.com",
    twitter: "judithadams",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 42,
    slug: "jeffrey-foster",
    name: "Dr. Jeffrey Foster",
    avatar: "/portraits/imgs30.jpg",
    affiliation: "Cambridge",
    communities: ["lesswrong", "ea"],
    topics: ["Decision Theory", "Natural Language Processing"],
    papers: 140,
    posts: 23,
    hIndex: 20,
    bio: "Researcher at OpenAI focusing on decision theory and natural language processing.",
    fullBio: "Dr. Jeffrey Foster is a researcher specializing in decision theory, natural language processing. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://jeffrey-foster.com",
    twitter: "jeffreyfoster",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 43,
    slug: "mark-brooks",
    name: "Dr. Mark Brooks",
    avatar: "/portraits/imgs31.jpg",
    affiliation: "Oxford FHI",
    communities: ["ea", "academic", "lesswrong"],
    topics: ["Game Theory", "Interpretability", "Ethics", "AI Governance"],
    papers: 148,
    posts: 32,
    hIndex: 18,
    bio: "Researcher at Anthropic focusing on game theory and interpretability.",
    fullBio: "Dr. Mark Brooks is a researcher specializing in game theory, interpretability, ethics, ai governance. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://mark-brooks.com",
    twitter: "markbrooks",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 44,
    slug: "walter-richardson",
    name: "Dr. Walter Richardson",
    avatar: "/portraits/imgs32.jpg",
    affiliation: "EleutherAI",
    communities: ["lesswrong"],
    topics: ["AI Governance", "Game Theory", "AI Safety", "Robotics"],
    papers: 85,
    posts: 24,
    hIndex: 29,
    bio: "Researcher at Carnegie Mellon University focusing on ai governance and game theory.",
    fullBio: "Dr. Walter Richardson is a researcher specializing in ai governance, game theory, ai safety, robotics. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://walter-richardson.com",
    twitter: "walterrichardson",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 45,
    slug: "jose-long",
    name: "Dr. Jose Long",
    avatar: "/portraits/imgs33.jpg",
    affiliation: "Google DeepMind",
    communities: ["academic"],
    topics: ["Robotics", "Decision Theory"],
    papers: 59,
    posts: 12,
    hIndex: 44,
    bio: "Researcher at Stanford HAI focusing on robotics and decision theory.",
    fullBio: "Dr. Jose Long is a researcher specializing in robotics, decision theory. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://jose-long.com",
    twitter: "joselong",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 46,
    slug: "nicole-barnes",
    name: "Dr. Nicole Barnes",
    avatar: "/portraits/imgs34.jpg",
    affiliation: "MIRI",
    communities: ["lesswrong"],
    topics: ["Robotics", "Ethics"],
    papers: 62,
    posts: 44,
    hIndex: 42,
    bio: "Researcher at Stanford HAI focusing on robotics and ethics.",
    fullBio: "Dr. Nicole Barnes is a researcher specializing in robotics, ethics. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://nicole-barnes.com",
    twitter: "nicolebarnes",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 47,
    slug: "harold-wood",
    name: "Dr. Harold Wood",
    avatar: "/portraits/imgs35.jpg",
    affiliation: "University of Toronto",
    communities: ["ea"],
    topics: ["AI Safety", "Neural Networks", "Computer Vision"],
    papers: 63,
    posts: 39,
    hIndex: 39,
    bio: "Researcher at Stanford HAI focusing on ai safety and neural networks.",
    fullBio: "Dr. Harold Wood is a researcher specializing in ai safety, neural networks, computer vision. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://harold-wood.com",
    twitter: "haroldwood",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 48,
    slug: "anna-green",
    name: "Dr. Anna Green",
    avatar: "/portraits/imgs36.jpg",
    affiliation: "Cambridge",
    communities: ["ea"],
    topics: ["AI Safety", "Reinforcement Learning", "Neural Networks", "Decision Theory"],
    papers: 27,
    posts: 36,
    hIndex: 42,
    bio: "Researcher at Cambridge focusing on ai safety and reinforcement learning.",
    fullBio: "Dr. Anna Green is a researcher specializing in ai safety, reinforcement learning, neural networks, decision theory. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://anna-green.com",
    twitter: "annagreen",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 49,
    slug: "andrea-jackson",
    name: "Dr. Andrea Jackson",
    avatar: "/portraits/imgs37.jpg",
    affiliation: "OpenAI",
    communities: ["lesswrong"],
    topics: ["Decision Theory", "Computer Vision", "Neural Networks"],
    papers: 17,
    posts: 16,
    hIndex: 11,
    bio: "Researcher at Carnegie Mellon University focusing on decision theory and computer vision.",
    fullBio: "Dr. Andrea Jackson is a researcher specializing in decision theory, computer vision, neural networks. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://andrea-jackson.com",
    twitter: "andreajackson",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 50,
    slug: "jose-ramirez",
    name: "Dr. Jose Ramirez",
    avatar: "/portraits/imgs38.jpg",
    affiliation: "Anthropic",
    communities: ["academic", "lesswrong"],
    topics: ["Computer Vision", "Large Language Models", "AI Governance"],
    papers: 35,
    posts: 31,
    hIndex: 55,
    bio: "Researcher at Carnegie Mellon University focusing on computer vision and large language models.",
    fullBio: "Dr. Jose Ramirez is a researcher specializing in computer vision, large language models, ai governance. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://jose-ramirez.com",
    twitter: "joseramirez",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 51,
    slug: "rachel-wilson",
    name: "Dr. Rachel Wilson",
    avatar: "/portraits/imgs39.jpg",
    affiliation: "Google DeepMind",
    communities: ["ea"],
    topics: ["AI Governance", "AI Safety"],
    papers: 103,
    posts: 10,
    hIndex: 40,
    bio: "Researcher at MIT CSAIL focusing on ai governance and ai safety.",
    fullBio: "Dr. Rachel Wilson is a researcher specializing in ai governance, ai safety. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://rachel-wilson.com",
    twitter: "rachelwilson",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 52,
    slug: "ashley-russell",
    name: "Dr. Ashley Russell",
    avatar: "/portraits/imgs40.jpg",
    affiliation: "Anthropic",
    communities: ["academic", "ea", "lesswrong"],
    topics: ["Computer Vision", "Robotics"],
    papers: 21,
    posts: 42,
    hIndex: 11,
    bio: "Researcher at Oxford FHI focusing on computer vision and robotics.",
    fullBio: "Dr. Ashley Russell is a researcher specializing in computer vision, robotics. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://ashley-russell.com",
    twitter: "ashleyrussell",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 53,
    slug: "terry-cox",
    name: "Dr. Terry Cox",
    avatar: "/portraits/imgs41.jpg",
    affiliation: "OpenAI",
    communities: ["academic", "lesswrong"],
    topics: ["Decision Theory", "Natural Language Processing", "Computer Vision", "Game Theory"],
    papers: 23,
    posts: 40,
    hIndex: 18,
    bio: "Researcher at Allen Institute for AI focusing on decision theory and natural language processing.",
    fullBio: "Dr. Terry Cox is a researcher specializing in decision theory, natural language processing, computer vision, game theory. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://terry-cox.com",
    twitter: "terrycox",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 54,
    slug: "randy-sanchez",
    name: "Dr. Randy Sanchez",
    avatar: "/portraits/imgs42.jpg",
    affiliation: "Stanford HAI",
    communities: ["lesswrong"],
    topics: ["Interpretability", "Neural Networks", "Decision Theory", "Natural Language Processing"],
    papers: 149,
    posts: 17,
    hIndex: 42,
    bio: "Researcher at Google DeepMind focusing on interpretability and neural networks.",
    fullBio: "Dr. Randy Sanchez is a researcher specializing in interpretability, neural networks, decision theory, natural language processing. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://randy-sanchez.com",
    twitter: "randysanchez",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 55,
    slug: "donald-king",
    name: "Dr. Donald King",
    avatar: "/portraits/imgs43.jpg",
    affiliation: "MIRI",
    communities: ["ea", "academic"],
    topics: ["Large Language Models", "Interpretability"],
    papers: 27,
    posts: 44,
    hIndex: 29,
    bio: "Researcher at EleutherAI focusing on large language models and interpretability.",
    fullBio: "Dr. Donald King is a researcher specializing in large language models, interpretability. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://donald-king.com",
    twitter: "donaldking",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 56,
    slug: "albert-watson",
    name: "Dr. Albert Watson",
    avatar: "/portraits/imgs44.jpg",
    affiliation: "UC Berkeley",
    communities: ["lesswrong"],
    topics: ["Ethics", "Robotics"],
    papers: 22,
    posts: 43,
    hIndex: 5,
    bio: "Researcher at Stanford HAI focusing on ethics and robotics.",
    fullBio: "Dr. Albert Watson is a researcher specializing in ethics, robotics. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://albert-watson.com",
    twitter: "albertwatson",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 57,
    slug: "christina-rivera",
    name: "Dr. Christina Rivera",
    avatar: "/portraits/imgs45.jpg",
    affiliation: "Cambridge",
    communities: ["academic", "lesswrong", "ea"],
    topics: ["Decision Theory", "Neural Networks", "Game Theory"],
    papers: 136,
    posts: 17,
    hIndex: 25,
    bio: "Researcher at Google DeepMind focusing on decision theory and neural networks.",
    fullBio: "Dr. Christina Rivera is a researcher specializing in decision theory, neural networks, game theory. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://christina-rivera.com",
    twitter: "christinarivera",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 58,
    slug: "willie-hughes",
    name: "Dr. Willie Hughes",
    avatar: "/portraits/imgs46.jpg",
    affiliation: "MIRI",
    communities: ["ea"],
    topics: ["AI Safety", "Large Language Models", "Reinforcement Learning"],
    papers: 36,
    posts: 12,
    hIndex: 24,
    bio: "Researcher at Anthropic focusing on ai safety and large language models.",
    fullBio: "Dr. Willie Hughes is a researcher specializing in ai safety, large language models, reinforcement learning. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://willie-hughes.com",
    twitter: "williehughes",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 59,
    slug: "victoria-johnson",
    name: "Dr. Victoria Johnson",
    avatar: "/portraits/imgs47.jpg",
    affiliation: "MIRI",
    communities: ["ea"],
    topics: ["Neural Networks", "AI Governance"],
    papers: 64,
    posts: 5,
    hIndex: 49,
    bio: "Researcher at UC Berkeley focusing on neural networks and ai governance.",
    fullBio: "Dr. Victoria Johnson is a researcher specializing in neural networks, ai governance. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://victoria-johnson.com",
    twitter: "victoriajohnson",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 60,
    slug: "harold-long",
    name: "Dr. Harold Long",
    avatar: "/portraits/imgs48.jpg",
    affiliation: "MIT CSAIL",
    communities: ["academic", "ea"],
    topics: ["Interpretability", "Reinforcement Learning", "Natural Language Processing", "Decision Theory"],
    papers: 131,
    posts: 6,
    hIndex: 5,
    bio: "Researcher at Allen Institute for AI focusing on interpretability and reinforcement learning.",
    fullBio: "Dr. Harold Long is a researcher specializing in interpretability, reinforcement learning, natural language processing, decision theory. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://harold-long.com",
    twitter: "haroldlong",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 61,
    slug: "arthur-flores",
    name: "Dr. Arthur Flores",
    avatar: "/portraits/imgs14.jpg",
    affiliation: "Allen Institute for AI",
    communities: ["lesswrong"],
    topics: ["Computer Vision", "AI Safety", "Interpretability"],
    papers: 80,
    posts: 32,
    hIndex: 54,
    bio: "Researcher at EleutherAI focusing on computer vision and ai safety.",
    fullBio: "Dr. Arthur Flores is a researcher specializing in computer vision, ai safety, interpretability. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://arthur-flores.com",
    twitter: "arthurflores",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 62,
    slug: "beverly-parker",
    name: "Dr. Beverly Parker",
    avatar: "/portraits/imgs1.jpg",
    affiliation: "UC Berkeley",
    communities: ["lesswrong"],
    topics: ["AI Safety", "Decision Theory"],
    papers: 149,
    posts: 34,
    hIndex: 53,
    bio: "Researcher at Oxford FHI focusing on ai safety and decision theory.",
    fullBio: "Dr. Beverly Parker is a researcher specializing in ai safety, decision theory. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://beverly-parker.com",
    twitter: "beverlyparker",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 63,
    slug: "nancy-clark",
    name: "Dr. Nancy Clark",
    avatar: "/portraits/imgs2.jpg",
    affiliation: "Google DeepMind",
    communities: ["ea", "academic"],
    topics: ["Game Theory", "Decision Theory", "Interpretability"],
    papers: 139,
    posts: 40,
    hIndex: 46,
    bio: "Researcher at MIRI focusing on game theory and decision theory.",
    fullBio: "Dr. Nancy Clark is a researcher specializing in game theory, decision theory, interpretability. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://nancy-clark.com",
    twitter: "nancyclark",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 64,
    slug: "terry-bryant",
    name: "Dr. Terry Bryant",
    avatar: "/portraits/imgs3.jpg",
    affiliation: "Anthropic",
    communities: ["academic", "lesswrong"],
    topics: ["Large Language Models", "Neural Networks"],
    papers: 44,
    posts: 34,
    hIndex: 13,
    bio: "Researcher at EleutherAI focusing on large language models and neural networks.",
    fullBio: "Dr. Terry Bryant is a researcher specializing in large language models, neural networks. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://terry-bryant.com",
    twitter: "terrybryant",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 65,
    slug: "judith-cox",
    name: "Dr. Judith Cox",
    avatar: "/portraits/imgs4.jpg",
    affiliation: "Carnegie Mellon University",
    communities: ["ea", "lesswrong"],
    topics: ["Reinforcement Learning", "Neural Networks", "Robotics", "Game Theory"],
    papers: 118,
    posts: 3,
    hIndex: 50,
    bio: "Researcher at Cambridge focusing on reinforcement learning and neural networks.",
    fullBio: "Dr. Judith Cox is a researcher specializing in reinforcement learning, neural networks, robotics, game theory. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://judith-cox.com",
    twitter: "judithcox",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 66,
    slug: "zachary-scott",
    name: "Dr. Zachary Scott",
    avatar: "/portraits/imgs5.jpg",
    affiliation: "Google DeepMind",
    communities: ["academic"],
    topics: ["Large Language Models", "AI Safety", "Neural Networks", "Game Theory"],
    papers: 124,
    posts: 13,
    hIndex: 55,
    bio: "Researcher at University of Toronto focusing on large language models and ai safety.",
    fullBio: "Dr. Zachary Scott is a researcher specializing in large language models, ai safety, neural networks, game theory. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://zachary-scott.com",
    twitter: "zacharyscott",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 67,
    slug: "steven-evans",
    name: "Dr. Steven Evans",
    avatar: "/portraits/imgs6.jpg",
    affiliation: "Carnegie Mellon University",
    communities: ["academic"],
    topics: ["Ethics", "Interpretability"],
    papers: 108,
    posts: 10,
    hIndex: 11,
    bio: "Researcher at Oxford FHI focusing on ethics and interpretability.",
    fullBio: "Dr. Steven Evans is a researcher specializing in ethics, interpretability. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://steven-evans.com",
    twitter: "stevenevans",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 68,
    slug: "matthew-coleman",
    name: "Dr. Matthew Coleman",
    avatar: "/portraits/imgs7.jpg",
    affiliation: "Allen Institute for AI",
    communities: ["lesswrong", "ea", "academic"],
    topics: ["Neural Networks", "AI Governance", "Computer Vision", "Large Language Models"],
    papers: 29,
    posts: 9,
    hIndex: 24,
    bio: "Researcher at Anthropic focusing on neural networks and ai governance.",
    fullBio: "Dr. Matthew Coleman is a researcher specializing in neural networks, ai governance, computer vision, large language models. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://matthew-coleman.com",
    twitter: "matthewcoleman",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 69,
    slug: "janice-bryant",
    name: "Dr. Janice Bryant",
    avatar: "/portraits/imgs8.jpg",
    affiliation: "OpenAI",
    communities: ["lesswrong"],
    topics: ["Ethics", "Large Language Models", "Decision Theory"],
    papers: 144,
    posts: 4,
    hIndex: 44,
    bio: "Researcher at EleutherAI focusing on ethics and large language models.",
    fullBio: "Dr. Janice Bryant is a researcher specializing in ethics, large language models, decision theory. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://janice-bryant.com",
    twitter: "janicebryant",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 70,
    slug: "matthew-adams",
    name: "Dr. Matthew Adams",
    avatar: "/portraits/imgs9.jpg",
    affiliation: "Oxford FHI",
    communities: ["ea"],
    topics: ["Reinforcement Learning", "Computer Vision", "Robotics"],
    papers: 17,
    posts: 14,
    hIndex: 37,
    bio: "Researcher at EleutherAI focusing on reinforcement learning and computer vision.",
    fullBio: "Dr. Matthew Adams is a researcher specializing in reinforcement learning, computer vision, robotics. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://matthew-adams.com",
    twitter: "matthewadams",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 71,
    slug: "danielle-jones",
    name: "Dr. Danielle Jones",
    avatar: "/portraits/imgs10.jpg",
    affiliation: "MIRI",
    communities: ["academic", "lesswrong"],
    topics: ["Robotics", "Ethics", "Interpretability"],
    papers: 80,
    posts: 49,
    hIndex: 10,
    bio: "Researcher at University of Toronto focusing on robotics and ethics.",
    fullBio: "Dr. Danielle Jones is a researcher specializing in robotics, ethics, interpretability. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://danielle-jones.com",
    twitter: "daniellejones",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 72,
    slug: "kelly-campbell",
    name: "Dr. Kelly Campbell",
    avatar: "/portraits/imgs11.jpg",
    affiliation: "Google DeepMind",
    communities: ["lesswrong", "ea", "academic"],
    topics: ["Ethics", "Decision Theory", "AI Governance", "Natural Language Processing"],
    papers: 125,
    posts: 10,
    hIndex: 18,
    bio: "Researcher at EleutherAI focusing on ethics and decision theory.",
    fullBio: "Dr. Kelly Campbell is a researcher specializing in ethics, decision theory, ai governance, natural language processing. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://kelly-campbell.com",
    twitter: "kellycampbell",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 73,
    slug: "marie-roberts",
    name: "Dr. Marie Roberts",
    avatar: "/portraits/imgs12.jpg",
    affiliation: "EleutherAI",
    communities: ["academic"],
    topics: ["AI Safety", "Ethics"],
    papers: 121,
    posts: 28,
    hIndex: 19,
    bio: "Researcher at University of Toronto focusing on ai safety and ethics.",
    fullBio: "Dr. Marie Roberts is a researcher specializing in ai safety, ethics. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://marie-roberts.com",
    twitter: "marieroberts",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 74,
    slug: "beverly-diaz",
    name: "Dr. Beverly Diaz",
    avatar: "/portraits/imgs13.jpg",
    affiliation: "EleutherAI",
    communities: ["lesswrong"],
    topics: ["Ethics", "Natural Language Processing", "Large Language Models"],
    papers: 25,
    posts: 25,
    hIndex: 30,
    bio: "Researcher at Google DeepMind focusing on ethics and natural language processing.",
    fullBio: "Dr. Beverly Diaz is a researcher specializing in ethics, natural language processing, large language models. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://beverly-diaz.com",
    twitter: "beverlydiaz",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 75,
    slug: "roy-baker",
    name: "Dr. Roy Baker",
    avatar: "/portraits/imgs15.jpg",
    affiliation: "University of Toronto",
    communities: ["lesswrong", "academic", "ea"],
    topics: ["Natural Language Processing", "Interpretability", "Robotics", "Large Language Models"],
    papers: 139,
    posts: 28,
    hIndex: 29,
    bio: "Researcher at OpenAI focusing on natural language processing and interpretability.",
    fullBio: "Dr. Roy Baker is a researcher specializing in natural language processing, interpretability, robotics, large language models. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://roy-baker.com",
    twitter: "roybaker",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 76,
    slug: "susan-hill",
    name: "Dr. Susan Hill",
    avatar: "/portraits/imgs16.jpg",
    affiliation: "OpenAI",
    communities: ["academic"],
    topics: ["Game Theory", "Ethics"],
    papers: 45,
    posts: 26,
    hIndex: 24,
    bio: "Researcher at Cambridge focusing on game theory and ethics.",
    fullBio: "Dr. Susan Hill is a researcher specializing in game theory, ethics. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://susan-hill.com",
    twitter: "susanhill",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 77,
    slug: "philip-white",
    name: "Dr. Philip White",
    avatar: "/portraits/imgs17.jpg",
    affiliation: "Allen Institute for AI",
    communities: ["lesswrong", "academic", "ea"],
    topics: ["Decision Theory", "Reinforcement Learning", "Natural Language Processing"],
    papers: 121,
    posts: 26,
    hIndex: 47,
    bio: "Researcher at MIT CSAIL focusing on decision theory and reinforcement learning.",
    fullBio: "Dr. Philip White is a researcher specializing in decision theory, reinforcement learning, natural language processing. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://philip-white.com",
    twitter: "philipwhite",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 78,
    slug: "judith-murphy",
    name: "Dr. Judith Murphy",
    avatar: "/portraits/imgs18.jpg",
    affiliation: "Stanford HAI",
    communities: ["lesswrong"],
    topics: ["Computer Vision", "Large Language Models", "Decision Theory"],
    papers: 97,
    posts: 14,
    hIndex: 14,
    bio: "Researcher at Cambridge focusing on computer vision and large language models.",
    fullBio: "Dr. Judith Murphy is a researcher specializing in computer vision, large language models, decision theory. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://judith-murphy.com",
    twitter: "judithmurphy",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 79,
    slug: "joyce-martin",
    name: "Dr. Joyce Martin",
    avatar: "/portraits/imgs19.jpg",
    affiliation: "Stanford HAI",
    communities: ["lesswrong", "academic"],
    topics: ["AI Governance", "Decision Theory", "AI Safety"],
    papers: 94,
    posts: 22,
    hIndex: 26,
    bio: "Researcher at MIRI focusing on ai governance and decision theory.",
    fullBio: "Dr. Joyce Martin is a researcher specializing in ai governance, decision theory, ai safety. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://joyce-martin.com",
    twitter: "joycemartin",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 80,
    slug: "catherine-wilson",
    name: "Dr. Catherine Wilson",
    avatar: "/portraits/imgs20.jpg",
    affiliation: "Carnegie Mellon University",
    communities: ["ea", "lesswrong"],
    topics: ["Decision Theory", "Interpretability", "Robotics"],
    papers: 16,
    posts: 50,
    hIndex: 48,
    bio: "Researcher at OpenAI focusing on decision theory and interpretability.",
    fullBio: "Dr. Catherine Wilson is a researcher specializing in decision theory, interpretability, robotics. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://catherine-wilson.com",
    twitter: "catherinewilson",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 81,
    slug: "alan-murphy",
    name: "Dr. Alan Murphy",
    avatar: "/portraits/imgs21.jpg",
    affiliation: "MIT CSAIL",
    communities: ["academic", "lesswrong", "ea"],
    topics: ["Large Language Models", "Decision Theory", "Computer Vision", "Reinforcement Learning"],
    papers: 97,
    posts: 45,
    hIndex: 35,
    bio: "Researcher at Stanford HAI focusing on large language models and decision theory.",
    fullBio: "Dr. Alan Murphy is a researcher specializing in large language models, decision theory, computer vision, reinforcement learning. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://alan-murphy.com",
    twitter: "alanmurphy",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 82,
    slug: "pamela-hernandez",
    name: "Dr. Pamela Hernandez",
    avatar: "/portraits/imgs22.jpg",
    affiliation: "EleutherAI",
    communities: ["lesswrong"],
    topics: ["Large Language Models", "Game Theory"],
    papers: 45,
    posts: 28,
    hIndex: 18,
    bio: "Researcher at Google DeepMind focusing on large language models and game theory.",
    fullBio: "Dr. Pamela Hernandez is a researcher specializing in large language models, game theory. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://pamela-hernandez.com",
    twitter: "pamelahernandez",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 83,
    slug: "angela-miller",
    name: "Dr. Angela Miller",
    avatar: "/portraits/imgs23.jpg",
    affiliation: "Anthropic",
    communities: ["academic"],
    topics: ["Large Language Models", "Reinforcement Learning", "Robotics", "Interpretability"],
    papers: 50,
    posts: 36,
    hIndex: 8,
    bio: "Researcher at Carnegie Mellon University focusing on large language models and reinforcement learning.",
    fullBio: "Dr. Angela Miller is a researcher specializing in large language models, reinforcement learning, robotics, interpretability. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://angela-miller.com",
    twitter: "angelamiller",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 84,
    slug: "virginia-stewart",
    name: "Dr. Virginia Stewart",
    avatar: "/portraits/imgs24.jpg",
    affiliation: "Allen Institute for AI",
    communities: ["lesswrong"],
    topics: ["AI Governance", "Interpretability", "Reinforcement Learning"],
    papers: 108,
    posts: 32,
    hIndex: 38,
    bio: "Researcher at Anthropic focusing on ai governance and interpretability.",
    fullBio: "Dr. Virginia Stewart is a researcher specializing in ai governance, interpretability, reinforcement learning. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://virginia-stewart.com",
    twitter: "virginiastewart",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 85,
    slug: "jason-cooper",
    name: "Dr. Jason Cooper",
    avatar: "/portraits/imgs25.jpg",
    affiliation: "UC Berkeley",
    communities: ["ea", "academic"],
    topics: ["Robotics", "Natural Language Processing", "Decision Theory", "Large Language Models"],
    papers: 122,
    posts: 30,
    hIndex: 24,
    bio: "Researcher at MIT CSAIL focusing on robotics and natural language processing.",
    fullBio: "Dr. Jason Cooper is a researcher specializing in robotics, natural language processing, decision theory, large language models. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://jason-cooper.com",
    twitter: "jasoncooper",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 86,
    slug: "kayla-price",
    name: "Dr. Kayla Price",
    avatar: "/portraits/imgs26.jpg",
    affiliation: "OpenAI",
    communities: ["academic", "lesswrong"],
    topics: ["Ethics", "AI Governance", "Computer Vision", "Neural Networks"],
    papers: 5,
    posts: 24,
    hIndex: 46,
    bio: "Researcher at Google DeepMind focusing on ethics and ai governance.",
    fullBio: "Dr. Kayla Price is a researcher specializing in ethics, ai governance, computer vision, neural networks. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://kayla-price.com",
    twitter: "kaylaprice",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 87,
    slug: "george-carter",
    name: "Dr. George Carter",
    avatar: "/portraits/imgs27.jpg",
    affiliation: "Allen Institute for AI",
    communities: ["ea", "lesswrong"],
    topics: ["Computer Vision", "AI Safety"],
    papers: 128,
    posts: 34,
    hIndex: 47,
    bio: "Researcher at Cambridge focusing on computer vision and ai safety.",
    fullBio: "Dr. George Carter is a researcher specializing in computer vision, ai safety. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://george-carter.com",
    twitter: "georgecarter",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 88,
    slug: "jason-thompson",
    name: "Dr. Jason Thompson",
    avatar: "/portraits/imgs28.jpg",
    affiliation: "Google DeepMind",
    communities: ["academic", "lesswrong", "ea"],
    topics: ["Reinforcement Learning", "AI Safety"],
    papers: 28,
    posts: 45,
    hIndex: 16,
    bio: "Researcher at Oxford FHI focusing on reinforcement learning and ai safety.",
    fullBio: "Dr. Jason Thompson is a researcher specializing in reinforcement learning, ai safety. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://jason-thompson.com",
    twitter: "jasonthompson",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 89,
    slug: "christine-evans",
    name: "Dr. Christine Evans",
    avatar: "/portraits/imgs29.jpg",
    affiliation: "Carnegie Mellon University",
    communities: ["academic", "ea"],
    topics: ["Large Language Models", "Robotics"],
    papers: 38,
    posts: 13,
    hIndex: 24,
    bio: "Researcher at Anthropic focusing on large language models and robotics.",
    fullBio: "Dr. Christine Evans is a researcher specializing in large language models, robotics. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://christine-evans.com",
    twitter: "christineevans",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 90,
    slug: "raymond-long",
    name: "Dr. Raymond Long",
    avatar: "/portraits/imgs30.jpg",
    affiliation: "OpenAI",
    communities: ["ea", "academic", "lesswrong"],
    topics: ["Reinforcement Learning", "Computer Vision", "Large Language Models", "Interpretability"],
    papers: 48,
    posts: 9,
    hIndex: 38,
    bio: "Researcher at MIRI focusing on reinforcement learning and computer vision.",
    fullBio: "Dr. Raymond Long is a researcher specializing in reinforcement learning, computer vision, large language models, interpretability. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://raymond-long.com",
    twitter: "raymondlong",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 91,
    slug: "julia-hughes",
    name: "Dr. Julia Hughes",
    avatar: "/portraits/imgs31.jpg",
    affiliation: "Stanford HAI",
    communities: ["academic", "ea"],
    topics: ["Ethics", "Decision Theory", "Reinforcement Learning"],
    papers: 137,
    posts: 5,
    hIndex: 29,
    bio: "Researcher at Cambridge focusing on ethics and decision theory.",
    fullBio: "Dr. Julia Hughes is a researcher specializing in ethics, decision theory, reinforcement learning. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://julia-hughes.com",
    twitter: "juliahughes",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 92,
    slug: "philip-price",
    name: "Dr. Philip Price",
    avatar: "/portraits/imgs32.jpg",
    affiliation: "Oxford FHI",
    communities: ["ea", "lesswrong"],
    topics: ["Decision Theory", "Game Theory", "Computer Vision"],
    papers: 105,
    posts: 1,
    hIndex: 48,
    bio: "Researcher at Cambridge focusing on decision theory and game theory.",
    fullBio: "Dr. Philip Price is a researcher specializing in decision theory, game theory, computer vision. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://philip-price.com",
    twitter: "philipprice",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 93,
    slug: "james-patterson",
    name: "Dr. James Patterson",
    avatar: "/portraits/imgs33.jpg",
    affiliation: "UC Berkeley",
    communities: ["lesswrong", "academic", "ea"],
    topics: ["Neural Networks", "Computer Vision", "Natural Language Processing"],
    papers: 44,
    posts: 11,
    hIndex: 37,
    bio: "Researcher at MIT CSAIL focusing on neural networks and computer vision.",
    fullBio: "Dr. James Patterson is a researcher specializing in neural networks, computer vision, natural language processing. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://james-patterson.com",
    twitter: "jamespatterson",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 94,
    slug: "melissa-johnson",
    name: "Dr. Melissa Johnson",
    avatar: "/portraits/imgs34.jpg",
    affiliation: "EleutherAI",
    communities: ["academic", "lesswrong", "ea"],
    topics: ["Large Language Models", "Reinforcement Learning", "Decision Theory", "Computer Vision"],
    papers: 133,
    posts: 30,
    hIndex: 25,
    bio: "Researcher at Oxford FHI focusing on large language models and reinforcement learning.",
    fullBio: "Dr. Melissa Johnson is a researcher specializing in large language models, reinforcement learning, decision theory, computer vision. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://melissa-johnson.com",
    twitter: "melissajohnson",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 95,
    slug: "justin-bennett",
    name: "Dr. Justin Bennett",
    avatar: "/portraits/imgs35.jpg",
    affiliation: "Oxford FHI",
    communities: ["ea", "lesswrong", "academic"],
    topics: ["Interpretability", "AI Governance", "Neural Networks"],
    papers: 112,
    posts: 50,
    hIndex: 36,
    bio: "Researcher at EleutherAI focusing on interpretability and ai governance.",
    fullBio: "Dr. Justin Bennett is a researcher specializing in interpretability, ai governance, neural networks. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://justin-bennett.com",
    twitter: "justinbennett",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 96,
    slug: "lauren-hernandez",
    name: "Dr. Lauren Hernandez",
    avatar: "/portraits/imgs36.jpg",
    affiliation: "Oxford FHI",
    communities: ["ea", "lesswrong"],
    topics: ["Neural Networks", "Ethics", "Interpretability", "Reinforcement Learning"],
    papers: 150,
    posts: 33,
    hIndex: 18,
    bio: "Researcher at EleutherAI focusing on neural networks and ethics.",
    fullBio: "Dr. Lauren Hernandez is a researcher specializing in neural networks, ethics, interpretability, reinforcement learning. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://lauren-hernandez.com",
    twitter: "laurenhernandez",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 97,
    slug: "brittany-moore",
    name: "Dr. Brittany Moore",
    avatar: "/portraits/imgs37.jpg",
    affiliation: "UC Berkeley",
    communities: ["academic", "lesswrong", "ea"],
    topics: ["Game Theory", "AI Governance", "Natural Language Processing", "Decision Theory"],
    papers: 64,
    posts: 45,
    hIndex: 28,
    bio: "Researcher at Google DeepMind focusing on game theory and ai governance.",
    fullBio: "Dr. Brittany Moore is a researcher specializing in game theory, ai governance, natural language processing, decision theory. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://brittany-moore.com",
    twitter: "brittanymoore",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 98,
    slug: "amanda-baker",
    name: "Dr. Amanda Baker",
    avatar: "/portraits/imgs38.jpg",
    affiliation: "UC Berkeley",
    communities: ["lesswrong"],
    topics: ["Robotics", "Reinforcement Learning", "Neural Networks"],
    papers: 34,
    posts: 42,
    hIndex: 58,
    bio: "Researcher at MIT CSAIL focusing on robotics and reinforcement learning.",
    fullBio: "Dr. Amanda Baker is a researcher specializing in robotics, reinforcement learning, neural networks. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://amanda-baker.com",
    twitter: "amandabaker",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 99,
    slug: "charlotte-kelly",
    name: "Dr. Charlotte Kelly",
    avatar: "/portraits/imgs39.jpg",
    affiliation: "Allen Institute for AI",
    communities: ["ea", "lesswrong"],
    topics: ["Natural Language Processing", "Game Theory", "Interpretability"],
    papers: 85,
    posts: 17,
    hIndex: 40,
    bio: "Researcher at Oxford FHI focusing on natural language processing and game theory.",
    fullBio: "Dr. Charlotte Kelly is a researcher specializing in natural language processing, game theory, interpretability. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://charlotte-kelly.com",
    twitter: "charlottekelly",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 100,
    slug: "bryan-parker",
    name: "Dr. Bryan Parker",
    avatar: "/portraits/imgs40.jpg",
    affiliation: "OpenAI",
    communities: ["academic"],
    topics: ["Robotics", "Natural Language Processing", "AI Governance"],
    papers: 79,
    posts: 22,
    hIndex: 7,
    bio: "Researcher at MIRI focusing on robotics and natural language processing.",
    fullBio: "Dr. Bryan Parker is a researcher specializing in robotics, natural language processing, ai governance. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://bryan-parker.com",
    twitter: "bryanparker",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 101,
    slug: "robert-morgan",
    name: "Dr. Robert Morgan",
    avatar: "/portraits/imgs41.jpg",
    affiliation: "UC Berkeley",
    communities: ["academic"],
    topics: ["Reinforcement Learning", "Robotics"],
    papers: 15,
    posts: 35,
    hIndex: 28,
    bio: "Researcher at Stanford HAI focusing on reinforcement learning and robotics.",
    fullBio: "Dr. Robert Morgan is a researcher specializing in reinforcement learning, robotics. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://robert-morgan.com",
    twitter: "robertmorgan",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 102,
    slug: "teresa-price",
    name: "Dr. Teresa Price",
    avatar: "/portraits/imgs42.jpg",
    affiliation: "University of Toronto",
    communities: ["academic", "ea"],
    topics: ["Reinforcement Learning", "Ethics"],
    papers: 89,
    posts: 34,
    hIndex: 26,
    bio: "Researcher at Oxford FHI focusing on reinforcement learning and ethics.",
    fullBio: "Dr. Teresa Price is a researcher specializing in reinforcement learning, ethics. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://teresa-price.com",
    twitter: "teresaprice",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 103,
    slug: "ethan-murphy",
    name: "Dr. Ethan Murphy",
    avatar: "/portraits/imgs43.jpg",
    affiliation: "OpenAI",
    communities: ["academic", "lesswrong", "ea"],
    topics: ["AI Governance", "Natural Language Processing", "Large Language Models"],
    papers: 94,
    posts: 0,
    hIndex: 9,
    bio: "Researcher at MIT CSAIL focusing on ai governance and natural language processing.",
    fullBio: "Dr. Ethan Murphy is a researcher specializing in ai governance, natural language processing, large language models. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://ethan-murphy.com",
    twitter: "ethanmurphy",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 104,
    slug: "catherine-smith",
    name: "Dr. Catherine Smith",
    avatar: "/portraits/imgs44.jpg",
    affiliation: "MIRI",
    communities: ["academic"],
    topics: ["Natural Language Processing", "Ethics", "Computer Vision"],
    papers: 79,
    posts: 33,
    hIndex: 17,
    bio: "Researcher at Allen Institute for AI focusing on natural language processing and ethics.",
    fullBio: "Dr. Catherine Smith is a researcher specializing in natural language processing, ethics, computer vision. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://catherine-smith.com",
    twitter: "catherinesmith",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 105,
    slug: "brenda-gonzales",
    name: "Dr. Brenda Gonzales",
    avatar: "/portraits/imgs45.jpg",
    affiliation: "Google DeepMind",
    communities: ["ea", "lesswrong"],
    topics: ["Large Language Models", "Game Theory", "Neural Networks", "Natural Language Processing"],
    papers: 12,
    posts: 0,
    hIndex: 28,
    bio: "Researcher at OpenAI focusing on large language models and game theory.",
    fullBio: "Dr. Brenda Gonzales is a researcher specializing in large language models, game theory, neural networks, natural language processing. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://brenda-gonzales.com",
    twitter: "brendagonzales",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 106,
    slug: "wayne-morgan",
    name: "Dr. Wayne Morgan",
    avatar: "/portraits/imgs46.jpg",
    affiliation: "OpenAI",
    communities: ["academic"],
    topics: ["Robotics", "Interpretability"],
    papers: 147,
    posts: 26,
    hIndex: 58,
    bio: "Researcher at UC Berkeley focusing on robotics and interpretability.",
    fullBio: "Dr. Wayne Morgan is a researcher specializing in robotics, interpretability. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://wayne-morgan.com",
    twitter: "waynemorgan",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 107,
    slug: "roger-alexander",
    name: "Dr. Roger Alexander",
    avatar: "/portraits/imgs47.jpg",
    affiliation: "Allen Institute for AI",
    communities: ["lesswrong"],
    topics: ["Interpretability", "AI Safety", "Neural Networks"],
    papers: 98,
    posts: 3,
    hIndex: 54,
    bio: "Researcher at Anthropic focusing on interpretability and ai safety.",
    fullBio: "Dr. Roger Alexander is a researcher specializing in interpretability, ai safety, neural networks. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://roger-alexander.com",
    twitter: "rogeralexander",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 108,
    slug: "natalie-ramirez",
    name: "Dr. Natalie Ramirez",
    avatar: "/portraits/imgs48.jpg",
    affiliation: "Cambridge",
    communities: ["academic", "lesswrong", "ea"],
    topics: ["Natural Language Processing", "Game Theory", "Interpretability"],
    papers: 87,
    posts: 22,
    hIndex: 50,
    bio: "Researcher at Allen Institute for AI focusing on natural language processing and game theory.",
    fullBio: "Dr. Natalie Ramirez is a researcher specializing in natural language processing, game theory, interpretability. They have published extensively in top-tier venues and are actively involved in the academic community.",
    website: "https://natalie-ramirez.com",
    twitter: "natalieramirez",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 109,
    slug: "emily-perez",
    name: "Dr. Emily Perez",
    avatar: "/portraits/imgs8.jpg",
    affiliation: "UC Berkeley",
    communities: ["ea", "lesswrong", "academic"],
    topics: ["AI Governance", "Neural Networks", "Ethics"],
    papers: 64,
    posts: 12,
    hIndex: 28,
    bio: "Researcher at Google DeepMind focusing on ai governance and neural networks.",
    fullBio: "Dr. Emily Perez is a researcher specializing in ai governance, neural networks, ethics. They have published extensively in top-tier venues and are actively involved in the ea community.",
    website: "https://emily-perez.com",
    twitter: "emilyperez",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
  {
    id: 110,
    slug: "mark-kelly",
    name: "Dr. Mark Kelly",
    avatar: "/portraits/imgs5.jpg",
    affiliation: "OpenAI",
    communities: ["lesswrong", "academic"],
    topics: ["Ethics", "AI Safety"],
    papers: 47,
    posts: 44,
    hIndex: 59,
    bio: "Researcher at MIT CSAIL focusing on ethics and ai safety.",
    fullBio: "Dr. Mark Kelly is a researcher specializing in ethics, ai safety. They have published extensively in top-tier venues and are actively involved in the lesswrong community.",
    website: "https://mark-kelly.com",
    twitter: "markkelly",
    publications: [],
    recentPosts: [],
    collaborators: [],
  },
]
